//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinium.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://infinium.2h.by/WebService1.asmx")]
        public string Infinium_WebService_WebService1 {
            get {
                return ((string)(this["Infinium_WebService_WebService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_light;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string LightConnectionString {
            get {
                return ((string)(this["LightConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_marketingorders;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string MarketingOrdersConnectionString {
            get {
                return ((string)(this["MarketingOrdersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_marketingreference;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string MarketingReferenceConnectionString {
            get {
                return ((string)(this["MarketingReferenceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_storage;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string StorageConnectionString {
            get {
                return ((string)(this["StorageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_users;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string UsersConnectionString {
            get {
                return ((string)(this["UsersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_zovorders;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string ZOVOrdersConnectionString {
            get {
                return ((string)(this["ZOVOrdersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_zovreference;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string ZOVReferenceConnectionString {
            get {
                return ((string)(this["ZOVReferenceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=infinium.zovprofil.by, 32433;Initial Catalog=infiniu2_catalog;Persist Security Info=True;Connection Timeout=10;User ID=infiniu2_infinium;Password=efcJzNcjJSEOpWfNsGmLRVkrCnnENR3VHSSN1J99CrwCPY5ipT5iPJ6xNViEiMaaZMvzKhQBby1FDzHp33CC/dpKdYXz4hQYG+oDE4mg+h6RBAZRY2kyThWXlF673UAh94GwyhcTuwFM2qAMEI5BpdsTFDnwwaHkzTV6MZG81pxcb0GtcwVIwfy22fX4d3+BUcMdqYeWodyWtxVRjOeuqQEN1iOxBAtsVUEWAcb2Ki4ZIKxzfudYtbBDiwsXrChAEGREFIf3kvn1jJjBTdx0ipdyftCC0PBctd6t1nNV2rI+p86/+GVUbBj5Z+VNkXSFEwFCusqqXIZsPWr9tZtFZWKrNdd5h9SoQv9jzmIWrnnhNH6awxMcSnRXu/DMNTJXw0A/1tj5Tz1ZFWo8pcHSLLmNWsh6EvYY3ctwH5HgZiySz++0X77Lrjn1Kjko0O0q")]
        public string CatalogConnectionString {
            get {
                return ((string)(this["CatalogConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://infinium.zovprofil.by/Update/UpdateInfinium/")]
        public string FTPType {
            get {
                return ((string)(this["FTPType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://infinium.zovprofil.by/Documents/")]
        public string DocumentsPath {
            get {
                return ((string)(this["DocumentsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://infinium.zovprofil.by/zovprofil.by/wwwroot/Images/")]
        public string DocumentsZOVTPSPath {
            get {
                return ((string)(this["DocumentsZOVTPSPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string Animation {
            get {
                return ((string)(this["Animation"]));
            }
        }
    }
}
